project 'assignment5.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'assignment5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for assignment5
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'

  target 'assignment5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'assignment5UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
